# Generated by Django 5.1 on 2024-08-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='encryption_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
