# Generated by Django 5.1 on 2024-08-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
