# Generated by Django 5.1 on 2024-08-20 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_message_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='key',
            field=models.CharField(blank=True, max_length=44, null=True),
        ),
    ]
